### ISSUE TITLE
What breakpoint library should I use?

### ISSUE THREAD

**Issue by jiangyuanluo** [bioinform/breakseq2#17]
I'm using a single bam file, hg19 as reference, and the breakpoint library dated 20150129, but breakseq does not produce any result. Is the breakpoint library only applicable to hg37? Should I use a different breakpoint library?

**Comment by YiweiNiu** [comment]
I have the same problem. I ran breakseq2 using hg38 as reference and got an empty vcf.

**Comment by marghoob** [comment]
Hi @jiangyuanluo and @YiweiNiu , the breakpoint library file should be in the same reference as the BAM being used. The BreakSeq library posted at http://sv.gersteinlab.org/phase1bkpts/breakseq2_bplib_20150129.zip seems to be for hg37. In order to use it with hg19, it would need to be modified to fix the chromosome names in the files to be hg19 style. For using the breakpoint library with hg38, it would need to be lifted over to hg38. One simple way is to lift the GFF file in the breakpoint library to hg38 and use the GFF as the input. However, this would only work for deletions. I am attaching a tar-gzipped archive of the library which should work for hg19. Please give it a try and let me know if it worked or not.

[breakseq2_bplib_20150129.hg19.tar.gz](https://github.com/bioinform/breakseq2/files/2229700/breakseq2_bplib_20150129.hg19.tar.gz)

**Comment by jiangyuanluo** [comment]
Hi @marghoob Thank you for providing the breakpoint library for hg19. I tested and it worked on my bam files.
